### ISSUE TITLE
Review and push contentmine docker image

### ISSUE THREAD

**Issue by de-code** [elifesciences/contentmine-docker#1]
@giorgiosironi would be nice to get a pipeline setup for this as well

(it takes a bit longer to build)

**Comment by giorgiosironi** [comment]
Added to project list in https://alfred.elifesciences.org/job/pull-requests-projects to build PRs.

**Comment by giorgiosironi** [comment]
Added https://alfred.elifesciences.org/job/image/job/image-contentmine pointing to `develop`.

**Comment by giorgiosironi** [comment]
Small problem in pushing in https://alfred.elifesciences.org/job/image/job/image-contentmine/1/console which I'll solve while integrating PRs (even if it will only be executed on the mainline).

**Comment by giorgiosironi** [comment]
In fact discovered https://alfred.elifesciences.org/job/image/job/image-metypeset/4/console has the same problem.

**Comment by de-code** [comment]
I think it's the `source .env` in `push.sh` (which overrides IMAGE_TAG).

**Comment by giorgiosironi** [comment]
Yes, it overwrites the variables, I'll standardize the pushing process.

**Comment by giorgiosironi** [comment]
Bugfix in https://github.com/elifesciences/metypeset-docker/commit/4a3a2deb02f73857bc7273537445476739e0625d

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/image/job/image-contentmine/ is green, close when satisfied.

**Comment by de-code** [comment]
Thanks, that's great.
